apps/store/urls.py
from django.urls import path, include
from .views import (
    ajax_set_product_info,
    product_list_view,
    product_detail_view,
    order_summary_view,
    ajax_add_to_cart,
    ajax_remove_item_from_cart,
    ajax_increase_item_from_cart,
    ajax_decrease_item_from_cart,
    ajax_get_product_info,
)

from rest_framework import routers
from .views import (
    OrderView, 
    OrderStatusView, 
    OrderItemView, 
    ProductView, 
    ProductAllergenView, 
    ProductLabelView, 
    ProductTypeView, 
    ProductUnitView, 
    PickupPointView
)

app_name = "store"

router = routers.DefaultRouter()
router.register(r'orders', OrderView, 'order')
router.register(r'order-items', OrderItemView, 'order_item')
router.register(r'order-statuses', OrderStatusView, 'order_status')
router.register(r'products', ProductView, 'product')
router.register(r'product-allergens', ProductAllergenView, 'product_allergen')
router.register(r'product-labels', ProductLabelView, 'product_label')
router.register(r'product-types', ProductTypeView, 'product_type')
router.register(r'product-units', ProductUnitView, 'product_unit')
router.register(r'pickup-points', PickupPointView, 'pickup_point')

urlpatterns = [
    path('products/', product_list_view, name="product_list"),
    path('product/<slug>/', product_detail_view, name="product"),
    path('ajax/add_to_cart/', ajax_add_to_cart, name="add_to_cart"),
    path('ajax/remove-item/', ajax_remove_item_from_cart, name="remove_item"),
    path('ajax/increase-item/', ajax_increase_item_from_cart, name="increase_item"),
    path('ajax/decrease-item/', ajax_decrease_item_from_cart, name="decrease_item"),
    
    path('order-summary/', order_summary_view, name="order_summary"),
    path('api/store/', include(router.urls)),

    path('get/ajax/get-product-info/', ajax_get_product_info, name="get_product_info"),
    path('post/ajax/set-product-info/', ajax_set_product_info, name="set_product_info"),
]

apps/userprofile/urls.py
from django.urls import path
from .views import (
    account_calendar_view,
    account_documents_view,
    account_products_view,
    account_sales_view,
    profile_view,
    account_dashboard_view,
    account_update_view,
    account_delete_view,
    account_message_board_view
)

urlpatterns = [
    path('profile/', profile_view, name="account_profile"),
    path('<int:pk>/profile/dashboard/', account_dashboard_view, name="account_dashboard"),
    path('<int:pk>/profile/update/', account_update_view, name='account_update'),
    path('<int:pk>/profile/message-board/', account_message_board_view, name='account_message_board'),
    path('<int:pk>/profile/delete/', account_delete_view, name='account_delete'),
    path('<int:pk>/profile/my-sales/', account_sales_view, name='my_sales'),
    path('<int:pk>/profile/my-products/', account_products_view, name='my_products'),
    path('<int:pk>/profile/my-calendar/', account_calendar_view, name='my_calendar'),
    path('<int:pk>/profile/my-documents/', account_documents_view, name='my_documents'),
]

we/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, include
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from .api import api_router

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns = urlpatterns + [
    path('', include('test_app.urls')),
    path('', include('store.urls', namespace="store")),
    path('', include('sales_pipeline.urls', namespace="sales_pipeline")),
    path('', include('userauth.urls')),
    path('', include('userprofile.urls')),
    path('', include('allauth.urls')),

    path('api/v2/', api_router.urls),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

apps/userprofile/models.py
from .forms import UserUpdateForm

from wagtail.admin.edit_handlers import (
    FieldPanel, InlinePanel, PageChooserPanel
)
from wagtail.core.models import Page
from wagtail.core.models import Orderable

from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.db import models
from django import forms

from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel

from django_extensions.db.fields import AutoSlugField

from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel,
    FieldRowPanel,
    InlinePanel,
    MultiFieldPanel
    
)

class ProfileMenuItem(Orderable):
    url = models.CharField(max_length=100, default="/", help_text="the relative url of the target page")
    title = models.CharField(max_length=30, default="")

    panels = [
        FieldPanel("url"),
        FieldPanel("title"),
    ]

    page = ParentalKey("ProfileMenu", related_name="menu_items")


class ProfileMenu(ClusterableModel):

    title = models.CharField(max_length=100)
    slug = AutoSlugField(
        populate_from="title",
        editable=True,
    )

    panels = [
        FieldPanel("title"),
        FieldPanel("slug"),
        InlinePanel("menu_items", label="Menu Item"),
    ]

    def __str__(self):
        menu_items = ProfileMenu.objects.get(slug=self.slug).menu_items.all()
        return self.title + ' - ' + str([item.title for item in menu_items])

apps/userprofile/forms.py
from userauth.models import User
from django import forms
from django.forms import ModelForm


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'birthdate', 'picture']
        widgets = {'birthdate': forms.DateInput(attrs={'type':'date'})}

apps/userprofile/views.py
from store.forms import ProductForm
from userauth.models import User, SupplierUser

from django.shortcuts import render
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import View, RedirectView
from django.urls import reverse_lazy
from .forms import UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from store.models import Product

@login_required
def profile_view(request):
        return redirect('account_dashboard', pk=request.user.pk)


@login_required
def account_dashboard_view(request, pk=0):
    return render(request, 'userprofile/account/account_dashboard.html')


class AccountUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('account_dashboard')
    template_name='userprofile/account/account_update.html'

account_update_view = login_required(AccountUpdateView.as_view())


@login_required
def account_message_board_view(request, pk=0):
    return render(request, 'userprofile/account/account_message_board.html')


class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('customer_signup')
    template_name='userauth/account/delete.html'

account_delete_view = login_required(AccountDeleteView.as_view())


@login_required
def account_sales_view(request, pk=0):
    return render(request, 'userprofile/account/account_sales.html')


@login_required
def account_products_view(request, pk=0):
    supplier = SupplierUser.objects.filter(user=request.user)[0]
    context = {
        'form': ProductForm(initial={'supplier': supplier}),
        'products': Product.objects.filter(supplier=supplier)
    }
    return render(request, 'userprofile/account/account_products.html', context)


@login_required
def account_calendar_view(request, pk=0):
    return render(request, 'userprofile/account/account_calendar.html')


@login_required
def account_documents_view(request, pk=0):
    return render(request, 'userprofile/account/account_documents.html')

apps/userprofile/templates/userprofile/account/account_calendar.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% load i18n static %}

{% block page_content %}
    <h4>My Calendar</h4>
{% endblock page_content %}

apps/userprofile/templates/userprofile/account/account_dashboard.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% load i18n static %}

{% block tab_title %}
    <h4>Dashboard</h4>
{% endblock tab_title %}

apps/userprofile/templates/userprofile/account/account_documents.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% load i18n static %}

{% block page_content %}
    <h4>My Documents</h4>
{% endblock page_content %}

apps/userprofile/templates/userprofile/account/account_message_board.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% block tab_title %}
    <h4>Message Board</h4>
{% endblock tab_title %}

apps/userprofile/templates/userprofile/account/account_products.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% load i18n static thumbnail %}

{% block page_content %}
<div class="background-container m-0 p-0 vh-100">

    <div class="mx-5 px-5">
        <h4 class="px-5">My Products</h4>
        <div class="px-3 table-bg">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Labels</th>
                        <th style="width: 5%;">In Stock</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        {% thumbnail product.image "150x100" crop="center" as im %}
                        <th class="p-0" style="width: 1%;"><img src="{{im.url}}" alt="{{product.image.alt}}"></th>
                        {% endthumbnail %}
                        <td>{{ product.name }}</td>
                        <td style="width: 1%;">{{ product.category }}</td>
                        <td>{{ product.description | safe }}</td>
                        <td>{{ product.allergens }}</td>
                        <td>{{product.quantity}}</td>
                        <td style="width: 1%;"><button onclick="edit('{{ product.slug }}')" class="btn btn-primary">Edit</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="p-4 table-bg">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#">«</a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="#">1</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">4</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">5</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">»</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Modal HTML -->
<div id="edit-modal" class="modal fade" tabindex="-1">

    <div class="modal-dialog modal-fullscreen mt-5">
        <div id="profile_content" class="modal-content" style="background-color: transparent">
            {% include './products/edit-product.html' %}
        </div>
    </div>
</div>
{% endblock page_content %}

{% block javascript %}
<script>

    function isChecked(checked_indices, id) {
        for (var j = 0 ; j < checked_indices.length ; ++j) {
            if (checked_indices[j] === id)
                return true;
        }
        return false;
    }

    function fillLabels(response) {
        var str = "<h5>Labels:</h5>"
        for (var i = 0 ; i < response['all_labels'].length ; ++i)
        {
            var lbl = response['all_labels'][i]
            var checked = isChecked(response['item']['labels'], lbl['id']);
            str += "<div class='col-6'>\n\
                <div class='form-check'>\n\
                    <input class='form-check-input' type='checkbox' "+ (checked?"checked":"unchecked") +" name='"+ lbl['id'] +"' id='label" + lbl['id'] + "'>\n\
                    <label class='form-check-label' for='label" + lbl['id'] + "'>" + lbl['name'] + "</label>\n\
                </div>\n</div>";
        }
        document.querySelector("#labels_block").innerHTML = str;
    }

    function fillAllergens(response) {
        var str = "<h5>Allergens:</h5>"
        for (var i = 0 ; i < response['all_allergens'].length ; ++i)
        {
            var lbl = response['all_allergens'][i]
            var checked = isChecked(response['item']['allergens'], lbl['id']);
            str += "<div class='form-check'>\n\
                <input class='form-check-input' type='checkbox' "+ (checked?"checked":"unchecked") +" name='"+ lbl['id'] +"' id='allergen" + lbl['id'] + "'>\n\
                <label class='form-check-label' for='allergen" + lbl['id'] + "'>" + lbl['name'] + "</label>\n\
            </div>";
        }
        document.querySelector("#allergens_block").innerHTML = str;
    }

    function fillTypes(response) {
        str = "<label for='item_type' class='form-label'>Select a category:</label>\n\
                <select class='form-select' id='item_type' name='type'>"

        for (var i = 0 ; i < response['all_types'].length ; ++i)
        {
            var lbl = response['all_types'][i]
            var selected = (response['item']['type'] === lbl['id']);

            str += "<option value='" + lbl['id'] + "' " + (selected?'selected':'') +">"+ lbl['name'] +"</option>";
        }
        str += "</select>"
        document.querySelector("#item_type").innerHTML = str;
    }


    function edit(item_id) {
        $.ajax({
            url: "{% url 'store:get_product_info' %}",
            dataType: "json",
            data: { slug: item_id},
            success: function (response) {
                document.getElementById("item_title").value = response['item']['name']
                document.getElementById("item_description").value = response['item']['description']
                document.getElementById("item_farmersadvice").value = response['item']['farmers_advice']

                fillLabels(response);
                fillAllergens(response);
                fillTypes(response);
            },
            error: function (response) {
                console.log('naaaay')
            }
        });


        $("#edit-modal").modal('show');
    }

    /*
    JS code for the browse button todo(@bmarques): 
    move button snippet into its own html file
    */
    const actualBtn = document.getElementById('actual-btn');
    const fileChosen = document.getElementById('file-chosen');

    actualBtn.addEventListener('change', function () {
        fileChosen.value = this.files[0].name
    })


    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#product-form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        console.log("SerializedData:\n" + serializedData)
        $.ajax({
            type: 'POST',
            url: "{% url 'store:set_product_info' %}",
            dataType: "json",
            data: { form: serializedData },
            success: function (response) {
                console.log("yaaay!!!")
            },
            error: function (response) {
                console.log("naaay...")
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }

        })
    })
</script>
{% endblock javascript %}

apps/userprofile/templates/userprofile/account/account_profile_base.html
{% extends 'userauth/account/base_profile_view.html' %}

{% load i18n static menu_tags %}
{% load i18n static string_tags %}

{% block profile_menus %}
    {% if request.user.is_supplier %}
        {% get_menu "supplierprofile" as menuitems %}

    {% elif request.user.is_manager %}
        {% get_menu "managerprofile" as menuitems %}
    {% else %}
        {% get_menu "customerprofile" as menuitems %}
    {% endif %}
    {% for item in menuitems.menu_items.all %}
            <a class="border-1 list-group-item list-group-item-action {% if request.resolver_match.url_name == item.url %}active{% endif %}"
             href="{% url item.url request.user.pk %}">
                {{item.title}}
            </a>
    {% endfor %}
{% endblock profile_menus %}

{% block javascript %}
    {# Override this in templates to add extra javascript #}
{% endblock javascript %}

apps/userprofile/templates/userprofile/account/account_sales.html
{% extends 'userprofile/account/account_profile_base.html' %}

{% load i18n static %}

{% block page_content %}
    <h4>My Sales</h4>
{% endblock page_content %}

apps/userprofile/templates/userprofile/account/account_update.html
{% extends 'userprofile/account/account_profile_base.html' %}
{% load i18n static %}


{% block page_content %}
{% load i18n socialaccount %}

    <div class="col-md-8">
        <h4 class="mb-5">Account Information</h4>
        {% get_providers as socialaccount_providers %}

        <form method="POST" action="{% url 'account_update' request.user.pk %}" enctype="multipart/form-data" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class= "col-md-4">
                    <img src="{{ request.user.picture.url }}" class="profile-image" alt="{% trans "User's profile Picture" %}" width="100%">
                </div>
                <div class= "col-md-8">
                    <div class="form-group">
                        <div class="form-row col-md-12">
                            {% with field=form.username default=request.user.username readonly="readonly" %}{% include "account/form_field.html" %}{% endwith %}
                        </div>
                        <div class="form-row col-md-12 mt-3">
                            {% with field=form.email default=request.user.email readonly="readonly" %}{% include "account/form_field.html" %}{% endwith %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-12">
                {% with field=form.picture default=request.user.picture %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-row col-md-12 mt-3">
                {% with field=form.first_name default=request.user.first_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-row col-md-12 mt-3">
                {% with field=form.last_name default=request.user.last_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-row col-md-4 mt-3">
                {% with field=form.birthdate default=request.user.birthdate %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <button type="submit" class="btn btn-outline-primary ml-2 mt-3">{% trans "Update" %}</button>
        </form>
    </div>
    <br>
    {% if socialaccount_providers %}
        <br>
        <p>{% blocktrans with site.name as site_name %}Connect your existing account to one of your social accounts:{% endblocktrans %}</p>
        {% include "socialaccount/provider_list.html" with process="connect" %}
    {% endif %}

{% endblock page_content %}