apps/store/urls.py
from django.urls import path, include
from .views import (
    ajax_set_product_info,
    product_list_view,
    product_detail_view,
    order_summary_view,
    ajax_add_to_cart,
    ajax_remove_item_from_cart,
    ajax_increase_item_from_cart,
    ajax_decrease_item_from_cart,
    ajax_get_product_info,
)

from rest_framework import routers
from .views import (
    OrderView, 
    OrderStatusView, 
    OrderItemView, 
    ProductView, 
    ProductAllergenView, 
    ProductLabelView, 
    ProductTypeView, 
    ProductUnitView, 
    PickupPointView
)

app_name = "store"

router = routers.DefaultRouter()
router.register(r'orders', OrderView, 'order')
router.register(r'order-items', OrderItemView, 'order_item')
router.register(r'order-statuses', OrderStatusView, 'order_status')
router.register(r'products', ProductView, 'product')
router.register(r'product-allergens', ProductAllergenView, 'product_allergen')
router.register(r'product-labels', ProductLabelView, 'product_label')
router.register(r'product-types', ProductTypeView, 'product_type')
router.register(r'product-units', ProductUnitView, 'product_unit')
router.register(r'pickup-points', PickupPointView, 'pickup_point')

urlpatterns = [
    path('products/', product_list_view, name="product_list"),
    path('product/<slug>/', product_detail_view, name="product"),
    path('ajax/add_to_cart/', ajax_add_to_cart, name="add_to_cart"),
    path('ajax/remove-item/', ajax_remove_item_from_cart, name="remove_item"),
    path('ajax/increase-item/', ajax_increase_item_from_cart, name="increase_item"),
    path('ajax/decrease-item/', ajax_decrease_item_from_cart, name="decrease_item"),
    
    path('order-summary/', order_summary_view, name="order_summary"),
    path('api/store/', include(router.urls)),

    path('get/ajax/get-product-info/', ajax_get_product_info, name="get_product_info"),
    path('post/ajax/set-product-info/', ajax_set_product_info, name="set_product_info"),
]

sales_pipeline/urls.py
from django.urls import path
from .views import (
    address_view,
    address_update_view,
    billing_view,
    payment_view,
)

app_name = "sales_pipeline"

urlpatterns = [
    path('address/', address_view, name="address"),
    path('address/<int:pk>', address_update_view, name="update_address"),
    path('billing/', billing_view, name="billing"),
    path('payment/', payment_view, name="payment"),
]

we/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, include
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from .api import api_router

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns = urlpatterns + [
    path('', include('test_app.urls')),
    path('', include('store.urls', namespace="store")),
    path('', include('sales_pipeline.urls', namespace="sales_pipeline")),
    path('', include('userauth.urls')),
    path('', include('userprofile.urls')),
    path('', include('allauth.urls')),

    path('api/v2/', api_router.urls),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r"", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

sales_pipeline/models.py
from django.db import models

# Create your models here.

sales_pipeline/forms.py
from django import forms
from django.utils.translation import gettext_lazy as tr

from userauth.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['name', 'first_name','last_name','address1','address2','country','city','zip_code', 'additional_information', 'is_primary']



class BillingForm(forms.Form):
    address = forms.ModelChoiceField(
        help_text=tr('Choose your billing address'), 
        queryset=Address.objects.all(), initial=0
    )
    customer_message = forms.CharField(
        required=False,
        help_text=tr('Do you want to leave us a message about your order?'), 
        widget=forms.Textarea(attrs={"rows":5, "cols":80})
    )

    # def __init__(self, *args, **kwargs):
    #     addr_qs = kwargs.get('queryset')
    #     kwargs.pop('queryset')
    #     super(forms.Form, self).__init__(*args, **kwargs)
    #     initial_set = False
    #     self.address = forms.ModelChoiceField(queryset=addr_qs)
    #     self.address.queryset
    #     i = 0
    #     for addr in addr_qs:
    #         if addr.is_primary:
    #             self.address.initial={str(i): addr}
    #             break
    #         i+=1

sales_pipeline/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import View, UpdateView, CreateView, FormView
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.core import serializers

from .forms import AddressForm, BillingForm
from userauth.models import Address
from store.models import Order


class SameUserOnlyMixin(object):

    def has_permissions(self):
        # Assumes that your Ticket model has a foreign key called user.
        return self.get_object().user == self.request.user

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permissions():
            return HttpResponseForbidden("You do not have permission to access this page")
        return super(SameUserOnlyMixin, self).dispatch(
            request, *args, **kwargs)


class AddressCreateView(CreateView):
    model = Address
    form_class = AddressForm
    success_url = reverse_lazy('sales_pipeline:billing')
    template_name='address.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

address_view = login_required(AddressCreateView.as_view())


class AddressUpdateView(SameUserOnlyMixin, UpdateView):
    model = Address
    form_class = AddressForm
    success_url = reverse_lazy('sales_pipeline:billing')
    template_name='address.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

address_update_view = login_required(AddressUpdateView.as_view())


class BillingView(FormView):
    template_name = 'billing.html'
    form_class = BillingForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(FormView, self).get_context_data(**kwargs)
        context['addrs'] = Address.objects.filter(user=context['view'].request.user)
        context['json_addrs'] = serializers.serialize('json', Address.objects.filter(user=context['view'].request.user).all())
        return context
        
    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        if form_class is None:
            form_class = self.get_form_class()
        form = form_class(**self.get_form_kwargs())
        if Address.objects.filter(user=self.request.user, is_primary=True).count():
            form.fields['address'].initial = Address.objects.filter(user=self.request.user, is_primary=True)[0]
        form.fields['address'].queryset = Address.objects.filter(user=self.request.user)
        return form

    def post(self, *args, **kwargs):
        form = BillingForm(self.request.POST or None)
        if form.is_valid():
            if self.request.POST.get('submit', '') == 'update_addr':
                messages.warning(self.request, 'updating address')
                return redirect('sales_pipeline:update_address', pk=form.cleaned_data['address'].pk)

            order_qs = Order.objects.filter(user=self.request.user, complete=False)
            if order_qs.exists():
                order = order_qs[0]
                order.address = form.cleaned_data['address']
                order.customer_message = form.cleaned_data['customer_message']
                order.save()
            return redirect('sales_pipeline:payment')
        else:
            print(self.request.POST)            
            messages.warning(self.request, 'oups, something went wrong: invalid form')
            return redirect('/')

billing_view = login_required(BillingView.as_view())


class PaymentView(View):
    template_name = 'payment.html'

    def get(self, *args, **kwargs):
            return render(self.request, self.template_name)

payment_view = login_required(PaymentView.as_view())

sales_pipeline/templates/address.html
{% extends 'sales-pipeline.html' %}
{% load crispy_forms_tags %}

{% block page_content %}

    <div class="container text-light" style="padding-top: 100px;">
      <div class="pt-5 text-center">
        <h2>{% if object.pk %}Update address "{{object.name}}"{% else %}Create a new Address{% endif %}</h2>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-10">
        <form method="post">
          {% csrf_token %}
          <div class="row px-0">
            <div class="col-md-6 mb-3 pl-0">
              {% with field=form.first_name placeholder="First name" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="col-md-6 mb-3 pr-0">
              {% with field=form.last_name placeholder="Last name"  field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
          </div>
          <div class="mb-3">
              {% with field=form.address1 placeholder="Address1" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
          </div>

          <div class="mb-3">
              {% with field=form.address2 placeholder="Address2" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
          </div>

          <div class="row">
            <div class="col-md-5 mb-3 pl-0">
              {% with field=form.country placeholder="Country" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="col-md-4 mb-3">
              {% with field=form.city placeholder="City" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="col-md-3 mb-3 pr-0">
              {% with field=form.zip_code placeholder="Zip code" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 mb-3 px-0">
              {% with field=form.additional_information placeholder="Additional information" field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 mb-3 px-0">
              {% with field=form.name field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="col-md-6 my-4 pl-5 pt-3 form-check">
            {% with "form-check-input input-field-"|add:form.is_primary.name as field_class %}
              <input type="checkbox" name="{{form.is_primary.name}}" id="check-is_primary" class="{{field_class}}">
              <label class="form-check-label" for="check-is_primary">
                  Set it as your default address?
              </label>
            {% endwith %}
            </div>
          </div>
          <hr class="mb-4">
          <button class="btn btn-success btn-lg btn-block mb-5" type="submit" value="Save">Save address</button>
        </form>
        </div>
      </div>
    </div>

{% endblock page_content %}

sales_pipeline/templates/billing.html
{% extends 'sales-pipeline.html' %}
{% block page_content %}

  <div class="row text-light">
    <div class="pt-5 text-center">
      <h2>Choose your billing address</h2>
    </div>
    <form method="POST">
      {% csrf_token %}
      <div class="row px-0">
        <div class="col-md-6 mb-3 pl-0">
            {% with field=form.address field_class="form-control" %}{% include "account/form_field.html" %}{% endwith %}
            <a href="{% url 'sales_pipeline:address' %}" class="btn btn-outline-success btn-lg btn-block my-3">Create a new Address</a>
            {% if addrs.all|first %}
              <h4>Your billing address:</h4>
              {% with addrs.all|first as addr %}
              <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col" id="addr-name">N/A</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td id="addr-first_name">N/A</td>
                  </tr>
                  <tr>
                    <td id="addr-address">N/A</td>
                  </tr>
                  <tr>
                    <td id="addr-zip_city">N/A</td>
                  <tr>
                    <td id="addr-country">N/A</td>
                  </tr>
                  <tr>
                    <td id="addr-phone">Phone: N/A</td>
                  </tr>
                  <tr>
                    <td id="addr-mobile">Mobile: N/A</td>
                  </tr>
                </tbody>
              </table>
              <div id="demo"></div>
              <button class="btn btn-outline-success btn-sm btn-block mb-5" type="submit" name="submit" value="update_addr">Update this address</button>
              {% endwith %}
            {% endif %}
        </div>
        <div class="col-md-6 mb-3 pr-0">
            <img src="../media/skultetyho_map.png" width="622" height="450" alt="a google map embed here" class="mb-4"/>
            {% with field=form.customer_message field_class="form-control"%}{% include "account/form_field.html" %}{% endwith %}
        </div>
      </div>
      <hr class="mb-4">
      <button class="btn btn-success btn-lg btn-block mb-5" type="submit" name="submit" value="to_checkout">Continue to checkout</button>
    </form>
  </div>

{% endblock page_content %}


{% block javascript %}
{% comment %} <script>
  function updateAddr(e) {
    e.preventDefault();
    var addresses = {{json_addrs|safe}};
    var pk = document.getElementById("id_address").value;
    for (var i = 0; i < addresses.length ; i+=1) {
      var addr = addresses[i];
      if (addr.pk.toString() === pk) {
        document.getElementById("addr-name").innerHTML = addr.fields.name.toString();
        document.getElementById("addr-first_name").innerHTML = addr.fields.first_name.toString() + " " + addr.fields.last_name.toString();
        document.getElementById("addr-address").innerHTML = addr.fields.address1.toString() + (addr.fields.address2 != null ? ", " + addr.fields.address2.toString() : "");
        document.getElementById("addr-zip_city").innerHTML = addr.fields.zip_code.toString() + " " + addr.fields.city.toString();
        document.getElementById("addr-country").innerHTML = addr.fields.country.toString();
        document.getElementById("addr-phone").innerHTML = "Phone: " + (addr.fields.phone == null ? "N/A" : addr.fields.phone.toString());
        document.getElementById("addr-mobile").innerHTML = "Mobile: " + (addr.fields.mobile_phone == null ? "N/A" : addr.fields.mobile_phone.toString());
        break;
      }
    }
  }

  window.addEventListener('load', function () {
    var addresses = {{json_addrs|safe}};
    var pk = document.getElementById("id_address").value;
    for (var i = 0; i < addresses.length ; i+=1) {
      var addr = addresses[i];
      if (addr.pk.toString() === pk) {
        document.getElementById("addr-name").innerHTML = addr.fields.name.toString();
        document.getElementById("addr-first_name").innerHTML = addr.fields.first_name.toString() + " " + addr.fields.last_name.toString();
        document.getElementById("addr-address").innerHTML = addr.fields.address1.toString() + (addr.fields.address2 != null ? ", " + addr.fields.address2.toString() : "");
        document.getElementById("addr-zip_city").innerHTML = addr.fields.zip_code.toString() + " " + addr.fields.city.toString();
        document.getElementById("addr-country").innerHTML = addr.fields.country.toString();
        document.getElementById("addr-phone").innerHTML = "Phone: " + (addr.fields.phone == null ? "N/A" : addr.fields.phone.toString());
        document.getElementById("addr-mobile").innerHTML = "Mobile: " + (addr.fields.mobile_phone == null ? "N/A" : addr.fields.mobile_phone.toString());
        break;
      }
    }
  })
  $("#id_address").on("change", function(e){ updateAddr(e); });

</script> {% endcomment %}
{% endblock javascript %}

sales_pipeline/templates/payment.html
{% extends 'sales-pipeline.html' %}
{% block page_content %}

    <div class="container text-light">
      <div class="row pt-5 text-center">
        <h2>Payment</h2>

        <div class="col-sm-4 card border-primary p-0">
            <div class="card-header">
                <h5>Choose your payment method:</h5>
            </div>
            <div class="bg-light m-0 p-3" id="paypal-button-container"></div>
        </div>
        <div class="col-sm-8 card border-primary p-0">
            <div class="card-header">
                <h5>Verify your order:</h5>
                <div class="bg-light text-dark my-5">
                ABC
                </div>
                <div class="bg-dark my-5">
                DEF
                </div>
                <div class="bg-light text-dark my-5">
                GHI
                </div>
                <div class="bg-dark my-5">
                JKL
                </div>
            </div>
        </div>
      </div>
      <div class="my-5">
      </div>
    </div>

{% endblock page_content %}


{% block javascript %}
<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

<script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.01'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
</script>
{% endblock javascript %}

sales_pipeline/templates/sales-pipeline.html
{% extends 'base.html' %}

{% block content %}
    <div class="row w-100 mx-5" style="padding-top: 100px;">
        <ol class="breadcrumb p-3">
        {% if request.path == "/order-summary/" %}
            <li class="breadcrumb-item active"><span>1. Summary</span></li>
        {% else %}
            <li class="breadcrumb-item">1. <a href="{% url 'store:order_summary' %}">Summary</a></li>
        {% endif %}

        {% if request.path == "/billing/" %}
            <li class="breadcrumb-item active"><span>2. Billing</span></li>
        {% else %}
            <li class="breadcrumb-item">2. <a href="{% url 'sales_pipeline:billing' %}">Billing</a></li>
        {% endif %}

        {% if request.path == "/payment/" %}
            <li class="breadcrumb-item active"><span>3. Payment</span></li>
        {% else %}
            <li class="breadcrumb-item">3. <a href="{% url 'sales_pipeline:payment' %}">Payment</a></li>
        {% endif %}
        </ol>
    {% block page_content %}{% endblock page_content %}
    </div>
{% endblock content %}